language: node_js
node_js:
  - "12"
services:
  - mongodb
before_script:
  - mongo library-test --eval 'db.createUser({ user:"travis", pwd:"test", roles:["readWrite"] });'
after_success:
- bash <(curl -s https://codecov.io/bash)
